### ISSUE TITLE
No `install.php` existent, Files apparently renamed, but README not updated

### ISSUE THREAD

**Issue by CBoensel** [FriendsOfShopware/1-file-installer#1]
### Actual behaviour

README.md mentions 

> Download the install.php and upload the file to your webspace

But no `install.php` located in the repo.

### Expected behaviour

file referenced that is present. 

### Steps to Reproduce?

Check the resources in the repo

**Comment by shyim** [comment]
The file from `https://install.fos.gg` is named later install.php

https://github.com/FriendsOfShopware/1-file-installer/blob/main/compile.php generates that file
